### ISSUE TITLE
Check minimum google-cloud-aiplatform version

### ISSUE THREAD

**Issue by efriis** [langchain-ai/langchain-google#103] opened 2024-03-28 22:18 UTC
User report of

Have you seen this with the google stuff?
ImportError: cannot import name 'telemetry' from 'google.cloud.aiplatform' (/usr/local/lib/python3.10/dist-packages/google/cloud/aiplatform/__init__.py)
on import of from langchain_google_vertexai import VertexAIEmbeddings, ChatVertexAI

Curious if maybe `telemetry` isn't available in a version of `google-cloud-aiplatform` that is acceptable in the version string in vertex pyproject.

Could also add minimum version release testing for that package in CI (along with langchain-core)

**Comment by lkuligin** [comment] 2024-03-29 05:36
Interesting, it was introduced by the 1.44.0:
https://github.com/googleapis/python-aiplatform/releases/tag/v1.44.0

and we require 1.44.0:
https://github.com/langchain-ai/langchain-google/blob/a13f3968239e53c3567a1ac0a6f23744f008ba4f/libs/vertexai/pyproject.toml#L16

**Comment by lkuligin** [comment] 2024-04-28 08:36
closing for now since no additional details have been provided by the user. let's reopen if we have a reproducible example.

**Closed by lkuligin** 2024-04-28 08:36 UTC
